import {
  adventure,
  autosell,
  availableAmount,
  bjornifyFamiliar,
  chew,
  cliExecute,
  drinksilent,
  eatsilent,
  equip,
  getClanId,
  getProperty,
  getStash,
  haveEffect,
  myAdventures,
  myClass,
  myFullness,
  myInebriety,
  mySpleenUse,
  print,
  putShop,
  putStash,
  spleenLimit,
  sweetSynthesis,
  sweetSynthesisPair,
  sweetSynthesisPairing,
  takeStash,
  use,
  useFamiliar,
  useSkill,
  visitUrl,
  runChoice,
  buy,
  setAutoAttack,
  maximize,
  faxbot,
  wait,
} from "kolmafia";
import {
  $coinmaster,
  $class,
  $effect,
  $familiar,
  $item,
  $location,
  $monster,
  $skill,
  $slot,
  adventureMacro,
  adventureMacroAuto,
  get,
  have,
  Macro,
} from "libram";
import { Digitize, getMaximumDigitizeUses } from "libram/dist/resources/SourceTerminal";
